// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXef46M5rSGr8ZXMlzmgsmBS6RtbopvQo',
    appId: '1:85253047935:web:abed39d250488bb829a14a',
    messagingSenderId: '85253047935',
    projectId: 'order-tracker-app-58daa',
    authDomain: 'order-tracker-app-58daa.firebaseapp.com',
    storageBucket: 'order-tracker-app-58daa.firebasestorage.app',
    measurementId: 'G-RWDNDK8XBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DOeWW82mpwhoQ4btkMj8wogSzHGcpx4',
    appId: '1:85253047935:android:77e4e2f96b1a402a29a14a',
    messagingSenderId: '85253047935',
    projectId: 'order-tracker-app-58daa',
    storageBucket: 'order-tracker-app-58daa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3xr0lDseR36qQfqJIDwChGahW78DTPhg',
    appId: '1:85253047935:ios:1b3f2b4330fc231229a14a',
    messagingSenderId: '85253047935',
    projectId: 'order-tracker-app-58daa',
    storageBucket: 'order-tracker-app-58daa.firebasestorage.app',
    iosBundleId: 'com.example.orderTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3xr0lDseR36qQfqJIDwChGahW78DTPhg',
    appId: '1:85253047935:ios:1b3f2b4330fc231229a14a',
    messagingSenderId: '85253047935',
    projectId: 'order-tracker-app-58daa',
    storageBucket: 'order-tracker-app-58daa.firebasestorage.app',
    iosBundleId: 'com.example.orderTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXef46M5rSGr8ZXMlzmgsmBS6RtbopvQo',
    appId: '1:85253047935:web:099498fb4ed4a89529a14a',
    messagingSenderId: '85253047935',
    projectId: 'order-tracker-app-58daa',
    authDomain: 'order-tracker-app-58daa.firebaseapp.com',
    storageBucket: 'order-tracker-app-58daa.firebasestorage.app',
    measurementId: 'G-JR60FW0VV0',
  );

}